// src/redux/types/groceryConsumptionTypes.js

// GET Grocery Consumption List
export const GROCERY_CONSUMPTION_LIST = {
    GROCERY_CONSUMPTION_LIST_START: "GROCERY_CONSUMPTION_LIST_START",
    GROCERY_CONSUMPTION_LIST_SUCCESS: "GROCERY_CONSUMPTION_LIST_SUCCESS",
    GROCERY_CONSUMPTION_LIST_FAIL: "GROCERY_CONSUMPTION_LIST_FAIL",
  };
  
  // ADD Grocery Consumption
  export const ADD_GROCERY_CONSUMPTION = {
    ADD_GROCERY_CONSUMPTION_START: "ADD_GROCERY_CONSUMPTION_START",
    ADD_GROCERY_CONSUMPTION_SUCCESS: "ADD_GROCERY_CONSUMPTION_SUCCESS",
    ADD_GROCERY_CONSUMPTION_FAIL: "ADD_GROCERY_CONSUMPTION_FAIL",
  };
  
  // DELETE Grocery Consumption
  export const DELETE_GROCERY_CONSUMPTION = {
    DELETE_GROCERY_CONSUMPTION_START: "DELETE_GROCERY_CONSUMPTION_START",
    DELETE_GROCERY_CONSUMPTION_SUCCESS: "DELETE_GROCERY_CONSUMPTION_SUCCESS",
    DELETE_GROCERY_CONSUMPTION_FAIL: "DELETE_GROCERY_CONSUMPTION_FAIL",
  };
  