// GET Notifications
export const NOTIFICATIONS_LIST = {
    NOTIFICATIONS_LIST_START: "NOTIFICATIONS_LIST_START",
    NOTIFICATIONS_LIST_SUCCESS: "NOTIFICATIONS_LIST_SUCCESS",
    NOTIFICATIONS_LIST_FAIL: "NOTIFICATIONS_LIST_FAIL",
  };
  