// src/redux/types/userTypes.js
export const USER_LIST = {
    USER_LIST_START: "USER_LIST_START",
    USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
    USER_LIST_FAIL: "USER_LIST_FAIL",
  };

// ✅ Add User Types
export const ADD_USER = {
    ADD_USER_START: "ADD_USER_START",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAIL: "ADD_USER_FAIL",
};

// ✅ Delete User Types
export const DELETE_USER = {
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",
};