// src/redux/types/supplierTypes.js
export const SUPPLIER_LIST = {
    SUPPLIER_LIST_START: "SUPPLIER_LIST_START",
    SUPPLIER_LIST_SUCCESS: "SUPPLIER_LIST_SUCCESS",
    SUPPLIER_LIST_FAIL: "SUPPLIER_LIST_FAIL",
  };

  export const ADD_SUPPLIER = {
    ADD_SUPPLIER_START: "ADD_SUPPLIER_START",
    ADD_SUPPLIER_SUCCESS: "ADD_SUPPLIER_SUCCESS",
    ADD_SUPPLIER_FAIL: "ADD_SUPPLIER_FAIL",
  };
  