export const base_url = 'http://15.206.123.114:5059/api';

export const loginUrl = `${base_url}/Token`;
export const studenturl = `${base_url}/Students`;
export const assetUrl = `${base_url}/Assets/GetAll`;
export const inventoryUrl = `${base_url}/Inventory/GetAll`;
export const staffUrl = `${base_url}/Staff`;
export const supplierUrl = `${base_url}/Suppliers`;
export const attendanceStudentUrl = `${base_url}/Attendance/students`;
export const attendanceStaffUrl = `${base_url}/Attendance/staff`;
export const itemTypeUrl = `${base_url}/Inventory/GetItemTypes`;
export const addInventoryItemUrl = `${base_url}/Inventory/Create`;
export const usersUrl = `${base_url}/Users/GetAll`;
export const addUsersUrl = `${base_url}/Users/Create`;
export const deleteUserUrl = (id) => `${base_url}/Users/Delete/${id}`;
export const rolesUrl = `${base_url}/Roles/GetAll`;
export const addRolesUrl = `${base_url}/Roles/Create`;
export const schoolsUrl = `${base_url}/School/GetAll`;
export const addSchoolsUrl = `${base_url}/School/Create`;
export const addAssetUrl = `${base_url}/Assets`;
export const departmentsUrl = `${base_url}/Lookup/departments`;
export const designationsUrl = `${base_url}/Lookup/designations`;
export const gradesUrl = `${base_url}/Lookup/grades`;
export const deleteAssetUrl = (id) => `${base_url}/Assets/${id}`;
export const deleteStaffUrl = (id) => `${base_url}/Staff/${id}`;
export const deleteSupplierUrl = (id) => `${base_url}/Suppliers/${id}`;
export const deleteRoleUrl = (id) => `${base_url}/Roles/Delete/${id}`;
export const deleteStudentUrl = (id) => `${base_url}/Students/${id}`;
export const deleteInventoryUrl = (id) => `${base_url}/Inventory/Delete/${id}`;