export const ROLES_LIST = {
    ROLES_LIST_START: "ROLES_LIST_START",
    ROLES_LIST_SUCCESS: "ROLES_LIST_SUCCESS",
    ROLES_LIST_FAIL: "ROLES_LIST_FAIL",
};

export const ADD_ROLE = {
    ADD_ROLE_START: "ADD_ROLE_START",
    ADD_ROLE_SUCCESS: "ADD_ROLE_SUCCESS",
    ADD_ROLE_FAIL: "ADD_ROLE_FAIL",
  };

export const DELETE_ROLE = {
    DELETE_ROLE_START: "DELETE_ROLE_START",
    DELETE_ROLE_SUCCESS: "DELETE_ROLE_SUCCESS",
    DELETE_ROLE_FAIL: "DELETE_ROLE_FAIL",
  };
  