// src/redux/types/staffTypes.js
export const STAFF_LIST = {
    STAFF_LIST_START: "STAFF_LIST_START",
    STAFF_LIST_SUCCESS: "STAFF_LIST_SUCCESS",
    STAFF_LIST_FAIL: "STAFF_LIST_FAIL",
  };

// src/redux/types/staffTypes.js
export const ADD_STAFF = {
  ADD_STAFF_START: "ADD_STAFF_START",
  ADD_STAFF_SUCCESS: "ADD_STAFF_SUCCESS",
  ADD_STAFF_FAIL: "ADD_STAFF_FAIL",
};

// src/redux/types/staffTypes.js
export const DELETE_STAFF = {
  DELETE_STAFF_START: "DELETE_STAFF_START",
  DELETE_STAFF_SUCCESS: "DELETE_STAFF_SUCCESS",
  DELETE_STAFF_FAIL: "DELETE_STAFF_FAIL",
};
