// src/redux/types/inventoryTypes.js
export const INVENTORY_LIST = {
    INVENTORY_LIST_START: "INVENTORY_LIST_START",
    INVENTORY_LIST_SUCCESS: "INVENTORY_LIST_SUCCESS",
    INVENTORY_LIST_FAIL: "INVENTORY_LIST_FAIL",
  };
  