// src/redux/types/inventoryTypes.js
export const INVENTORY_LIST = {
    INVENTORY_LIST_START: "INVENTORY_LIST_START",
    INVENTORY_LIST_SUCCESS: "INVENTORY_LIST_SUCCESS",
    INVENTORY_LIST_FAIL: "INVENTORY_LIST_FAIL",
  };

// src/redux/types/inventoryTypes.js
export const ITEM_TYPE_LIST = {
    ITEM_TYPE_LIST_START: "ITEM_TYPE_LIST_START",
    ITEM_TYPE_LIST_SUCCESS: "ITEM_TYPE_LIST_SUCCESS",
    ITEM_TYPE_LIST_FAIL: "ITEM_TYPE_LIST_FAIL",
  };

// src/redux/types/inventoryTypes.js
export const ADD_INVENTORY_ITEM = {
    ADD_INVENTORY_ITEM_START: "ADD_INVENTORY_ITEM_START",
    ADD_INVENTORY_ITEM_SUCCESS: "ADD_INVENTORY_ITEM_SUCCESS",
    ADD_INVENTORY_ITEM_FAIL: "ADD_INVENTORY_ITEM_FAIL",
  };
  
// src/redux/types/inventoryTypes.js
export const DELETE_INVENTORY_ITEM = {
  DELETE_INVENTORY_ITEM_START: "DELETE_INVENTORY_ITEM_START",
  DELETE_INVENTORY_ITEM_SUCCESS: "DELETE_INVENTORY_ITEM_SUCCESS",
  DELETE_INVENTORY_ITEM_FAIL: "DELETE_INVENTORY_ITEM_FAIL",
};

// ⭐ NEW: get_items_list
export const GET_ITEMS_LIST = {
  GET_ITEMS_LIST_START: "GET_ITEMS_LIST_START",
  GET_ITEMS_LIST_SUCCESS: "GET_ITEMS_LIST_SUCCESS",
  GET_ITEMS_LIST_FAIL: "GET_ITEMS_LIST_FAIL",
};

// ⭐ NEW: INVENTORY_ITEM
export const INVENTORY_ITEM = {
  INVENTORY_ITEM_START: "INVENTORY_ITEM_START",
  INVENTORY_ITEM_SUCCESS: "INVENTORY_ITEM_SUCCESS",
  INVENTORY_ITEM_FAIL: "INVENTORY_ITEM_FAIL",
};
