// src/redux/types/attendanceTypes.js
export const ATTENDANCE_STUDENT_LIST = {
    ATTENDANCE_STUDENT_LIST_START: "ATTENDANCE_STUDENT_LIST_START",
    ATTENDANCE_STUDENT_LIST_SUCCESS: "ATTENDANCE_STUDENT_LIST_SUCCESS",
    ATTENDANCE_STUDENT_LIST_FAIL: "ATTENDANCE_STUDENT_LIST_FAIL",
};

// src/redux/types/attendanceTypes.js
export const ATTENDANCE_STAFF_LIST = {
    ATTENDANCE_STAFF_LIST_START: "ATTENDANCE_STAFF_LIST_START",
    ATTENDANCE_STAFF_LIST_SUCCESS: "ATTENDANCE_STAFF_LIST_SUCCESS",
    ATTENDANCE_STAFF_LIST_FAIL: "ATTENDANCE_STAFF_LIST_FAIL",
  };
  