// src/redux/types/attendanceTypes.js
export const ATTENDANCE_STUDENT_LIST = {
    ATTENDANCE_STUDENT_LIST_START: "ATTENDANCE_STUDENT_LIST_START",
    ATTENDANCE_STUDENT_LIST_SUCCESS: "ATTENDANCE_STUDENT_LIST_SUCCESS",
    ATTENDANCE_STUDENT_LIST_FAIL: "ATTENDANCE_STUDENT_LIST_FAIL",
};

// src/redux/types/attendanceTypes.js
export const ATTENDANCE_STAFF_LIST = {
    ATTENDANCE_STAFF_LIST_START: "ATTENDANCE_STAFF_LIST_START",
    ATTENDANCE_STAFF_LIST_SUCCESS: "ATTENDANCE_STAFF_LIST_SUCCESS",
    ATTENDANCE_STAFF_LIST_FAIL: "ATTENDANCE_STAFF_LIST_FAIL",
  };

// src/redux/types/attendanceTypes.js
export const ADD_STAFF_ATTENDANCE = {
    ADD_STAFF_ATTENDANCE_START: "ADD_STAFF_ATTENDANCE_START",
    ADD_STAFF_ATTENDANCE_SUCCESS: "ADD_STAFF_ATTENDANCE_SUCCESS",
    ADD_STAFF_ATTENDANCE_FAIL: "ADD_STAFF_ATTENDANCE_FAIL",
  };

  export const ADD_STUDENT_ATTENDANCE = {
    ADD_STUDENT_ATTENDANCE_START: "ADD_STUDENT_ATTENDANCE_START",
    ADD_STUDENT_ATTENDANCE_SUCCESS: "ADD_STUDENT_ATTENDANCE_SUCCESS",
    ADD_STUDENT_ATTENDANCE_FAIL: "ADD_STUDENT_ATTENDANCE_FAIL",
  };
  