// src/redux/types/activityTypes.js

// GET Activities
export const ACTIVITY_LIST = {
    ACTIVITY_LIST_START: "ACTIVITY_LIST_START",
    ACTIVITY_LIST_SUCCESS: "ACTIVITY_LIST_SUCCESS",
    ACTIVITY_LIST_FAIL: "ACTIVITY_LIST_FAIL",
  };
  
  // ADD Activity
  export const ADD_ACTIVITY = {
    ADD_ACTIVITY_START: "ADD_ACTIVITY_START",
    ADD_ACTIVITY_SUCCESS: "ADD_ACTIVITY_SUCCESS",
    ADD_ACTIVITY_FAIL: "ADD_ACTIVITY_FAIL",
  };
  
  // DELETE Activity
  export const DELETE_ACTIVITY = {
    DELETE_ACTIVITY_START: "DELETE_ACTIVITY_START",
    DELETE_ACTIVITY_SUCCESS: "DELETE_ACTIVITY_SUCCESS",
    DELETE_ACTIVITY_FAIL: "DELETE_ACTIVITY_FAIL",
  };
  