// src/redux/types/studentTypes.js
export const STUDENT_LIST = {
  STUDENT_LIST_START: "STUDENT_LIST_START",
  STUDENT_LIST_SUCCESS: "STUDENT_LIST_SUCCESS",
  STUDENT_LIST_FAIL: "STUDENT_LIST_FAIL",
};

// src/redux/types/studentTypes.js
export const ADD_STUDENT = {
  ADD_STUDENT_START: "ADD_STUDENT_START",
  ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
  ADD_STUDENT_FAIL: "ADD_STUDENT_FAIL",
};

export const DELETE_STUDENT = {
  DELETE_STUDENT_START: "DELETE_STUDENT_START",
  DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAIL: "DELETE_STUDENT_FAIL",
};

export const GET_STUDENT_BY_GRADE = {
  GET_STUDENT_BY_GRADE_START: "GET_STUDENT_BY_GRADE_START",
  GET_STUDENT_BY_GRADE_SUCCESS: "GET_STUDENT_BY_GRADE_SUCCESS",
  GET_STUDENT_BY_GRADE_FAIL: "GET_STUDENT_BY_GRADE_FAIL",
};
