// src/redux/types/studentTypes.js
export const STUDENT_LIST = {
  STUDENT_LIST_START: "STUDENT_LIST_START",
  STUDENT_LIST_SUCCESS: "STUDENT_LIST_SUCCESS",
  STUDENT_LIST_FAIL: "STUDENT_LIST_FAIL",
};
