// src/redux/types/studentTypes.js
export const STUDENT_LIST = {
  STUDENT_LIST_START: "STUDENT_LIST_START",
  STUDENT_LIST_SUCCESS: "STUDENT_LIST_SUCCESS",
  STUDENT_LIST_FAIL: "STUDENT_LIST_FAIL",
};

// src/redux/types/studentTypes.js
export const ADD_STUDENT = {
  ADD_STUDENT_START: "ADD_STUDENT_START",
  ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
  ADD_STUDENT_FAIL: "ADD_STUDENT_FAIL",
};
