// src/redux/types/departmentsTypes.js
export const DEPARTMENTS_LIST = {
    DEPARTMENTS_LIST_START: "DEPARTMENTS_LIST_START",
    DEPARTMENTS_LIST_SUCCESS: "DEPARTMENTS_LIST_SUCCESS",
    DEPARTMENTS_LIST_FAIL: "DEPARTMENTS_LIST_FAIL",
  };

// src/redux/types/designationsTypes.js
export const DESIGNATIONS_LIST = {
    DESIGNATIONS_LIST_START: "DESIGNATIONS_LIST_START",
    DESIGNATIONS_LIST_SUCCESS: "DESIGNATIONS_LIST_SUCCESS",
    DESIGNATIONS_LIST_FAIL: "DESIGNATIONS_LIST_FAIL",
  };

export const GRADES_LIST = {
    GRADES_LIST_START: "GRADES_LIST_START",
    GRADES_LIST_SUCCESS: "GRADES_LIST_SUCCESS",
    GRADES_LIST_FAIL: "GRADES_LIST_FAIL",
  };
  