// src/redux/types/departmentsTypes.js
export const DEPARTMENTS_LIST = {
    DEPARTMENTS_LIST_START: "DEPARTMENTS_LIST_START",
    DEPARTMENTS_LIST_SUCCESS: "DEPARTMENTS_LIST_SUCCESS",
    DEPARTMENTS_LIST_FAIL: "DEPARTMENTS_LIST_FAIL",
  };

// src/redux/types/designationsTypes.js
export const DESIGNATIONS_LIST = {
    DESIGNATIONS_LIST_START: "DESIGNATIONS_LIST_START",
    DESIGNATIONS_LIST_SUCCESS: "DESIGNATIONS_LIST_SUCCESS",
    DESIGNATIONS_LIST_FAIL: "DESIGNATIONS_LIST_FAIL",
  };

export const GRADES_LIST = {
    GRADES_LIST_START: "GRADES_LIST_START",
    GRADES_LIST_SUCCESS: "GRADES_LIST_SUCCESS",
    GRADES_LIST_FAIL: "GRADES_LIST_FAIL",
  };

// ✅ Added categories list
export const CATEGORIES_LIST = {
  CATEGORIES_LIST_START: "CATEGORIES_LIST_START",
  CATEGORIES_LIST_SUCCESS: "CATEGORIES_LIST_SUCCESS",
  CATEGORIES_LIST_FAIL: "CATEGORIES_LIST_FAIL",
};

export const ATTENDANCE_TYPES_LIST = {
  ATTENDANCE_TYPES_LIST_START: "ATTENDANCE_TYPES_LIST_START",
  ATTENDANCE_TYPES_LIST_SUCCESS: "ATTENDANCE_TYPES_LIST_SUCCESS",
  ATTENDANCE_TYPES_LIST_FAIL: "ATTENDANCE_TYPES_LIST_FAIL",
};

// Item Types List
export const ITEM_TYPES_LIST = {
  ITEM_TYPES_LIST_START: "ITEM_TYPES_LIST_START",
  ITEM_TYPES_LIST_SUCCESS: "ITEM_TYPES_LIST_SUCCESS",
  ITEM_TYPES_LIST_FAIL: "ITEM_TYPES_LIST_FAIL",
};



// ADD Departments
export const ADD_DEPARTMENTS = {
  ADD_DEPARTMENTS_START: "ADD_DEPARTMENTS_START",
  ADD_DEPARTMENTS_SUCCESS: "ADD_DEPARTMENTS_SUCCESS",
  ADD_DEPARTMENTS_FAIL: "ADD_DEPARTMENTS_FAIL",
};

// ADD Designations
export const ADD_DESIGNATIONS = {
  ADD_DESIGNATIONS_START: "ADD_DESIGNATIONS_START",
  ADD_DESIGNATIONS_SUCCESS: "ADD_DESIGNATIONS_SUCCESS",
  ADD_DESIGNATIONS_FAIL: "ADD_DESIGNATIONS_FAIL",
};

// ADD Grades
export const ADD_GRADES = {
  ADD_GRADES_START: "ADD_GRADES_START",
  ADD_GRADES_SUCCESS: "ADD_GRADES_SUCCESS",
  ADD_GRADES_FAIL: "ADD_GRADES_FAIL",
};

// ADD Categories
export const ADD_CATEGORIES = {
  ADD_CATEGORIES_START: "ADD_CATEGORIES_START",
  ADD_CATEGORIES_SUCCESS: "ADD_CATEGORIES_SUCCESS",
  ADD_CATEGORIES_FAIL: "ADD_CATEGORIES_FAIL",
};

// ADD Attendance Types
export const ADD_ATTENDANCE_TYPES = {
  ADD_ATTENDANCE_TYPES_START: "ADD_ATTENDANCE_TYPES_START",
  ADD_ATTENDANCE_TYPES_SUCCESS: "ADD_ATTENDANCE_TYPES_SUCCESS",
  ADD_ATTENDANCE_TYPES_FAIL: "ADD_ATTENDANCE_TYPES_FAIL",
};

// ADD Item Types
export const ADD_ITEM_TYPES = {
  ADD_ITEM_TYPES_START: "ADD_ITEM_TYPES_START",
  ADD_ITEM_TYPES_SUCCESS: "ADD_ITEM_TYPES_SUCCESS",
  ADD_ITEM_TYPES_FAIL: "ADD_ITEM_TYPES_FAIL",
};
