// src/redux/types/holidayTypes.js

// GET Holidays
export const HOLIDAY_LIST = {
    HOLIDAY_LIST_START: "HOLIDAY_LIST_START",
    HOLIDAY_LIST_SUCCESS: "HOLIDAY_LIST_SUCCESS",
    HOLIDAY_LIST_FAIL: "HOLIDAY_LIST_FAIL",
  };
  
  // ADD Holiday
  export const ADD_HOLIDAY = {
    ADD_HOLIDAY_START: "ADD_HOLIDAY_START",
    ADD_HOLIDAY_SUCCESS: "ADD_HOLIDAY_SUCCESS",
    ADD_HOLIDAY_FAIL: "ADD_HOLIDAY_FAIL",
  };
  
  // DELETE Holiday
  export const DELETE_HOLIDAY = {
    DELETE_HOLIDAY_START: "DELETE_HOLIDAY_START",
    DELETE_HOLIDAY_SUCCESS: "DELETE_HOLIDAY_SUCCESS",
    DELETE_HOLIDAY_FAIL: "DELETE_HOLIDAY_FAIL",
  };
  